# Generated by Django 4.1 on 2022-08-25 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usd', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Курс доллара',
            },
        ),
        migrations.CreateModel(
            name='TourInCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image1', models.ImageField(upload_to='tour_image/')),
                ('image2', models.ImageField(upload_to='tour_image/')),
                ('location', models.TextField()),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('popular', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Туры внутри страны',
            },
        ),
        migrations.CreateModel(
            name='TourOutCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image1', models.ImageField(upload_to='tour_image/')),
                ('image2', models.ImageField(upload_to='tour_image/')),
                ('location', models.TextField()),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('popular', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.country')),
            ],
            options={
                'verbose_name_plural': 'Туры за рубежом',
            },
        ),
        migrations.CreateModel(
            name='TourOutCountryRoadMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='tour_image/')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.touroutcountry')),
            ],
            options={
                'verbose_name_plural': 'Маршрут',
            },
        ),
        migrations.CreateModel(
            name='TourOutCountryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tour_image/')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.touroutcountry')),
            ],
            options={
                'verbose_name_plural': 'Добавить больше фото',
            },
        ),
        migrations.CreateModel(
            name='TourInCountryRoadMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='tour_image/')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.tourincountry')),
            ],
            options={
                'verbose_name_plural': 'Маршрут',
            },
        ),
        migrations.CreateModel(
            name='TourInCountryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tour_image/')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.tourincountry')),
            ],
            options={
                'verbose_name_plural': 'Добавить больше фото',
            },
        ),
    ]
