# Generated by Django 4.1 on 2022-08-26 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_tourincountryroadmap_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='banner_file/')),
            ],
            options={
                'verbose_name_plural': 'Баннер',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='BannerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(upload_to='banner_file/')),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.banner')),
            ],
            options={
                'verbose_name_plural': 'Баннер файлы',
                'ordering': ('-id',),
            },
        ),
    ]
