# Generated by Django 4.1 on 2022-08-26 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_banner_bannerimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerAboutUsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('file1', models.FileField(upload_to='banner_file/')),
                ('file2', models.FileField(upload_to='banner_file/')),
                ('file3', models.FileField(upload_to='banner_file/')),
            ],
            options={
                'verbose_name_plural': 'Баннер для страница О нас',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='BannerHomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file1', models.FileField(upload_to='banner_file/')),
                ('file2', models.FileField(upload_to='banner_file/')),
                ('file3', models.FileField(upload_to='banner_file/')),
            ],
            options={
                'verbose_name_plural': 'Баннер для главного страница',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='BannerNewsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('file1', models.FileField(upload_to='banner_file/')),
                ('file2', models.FileField(upload_to='banner_file/')),
                ('file3', models.FileField(upload_to='banner_file/')),
            ],
            options={
                'verbose_name_plural': 'Баннер для страница новастей',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='BannerTourPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('file1', models.FileField(upload_to='banner_file/')),
                ('file2', models.FileField(upload_to='banner_file/')),
                ('file3', models.FileField(upload_to='banner_file/')),
            ],
            options={
                'verbose_name_plural': 'Баннер для тур страницы',
                'ordering': ('-id',),
            },
        ),
        migrations.RemoveField(
            model_name='bannerimage',
            name='banner',
        ),
        migrations.DeleteModel(
            name='Banner',
        ),
        migrations.DeleteModel(
            name='BannerImage',
        ),
    ]
