# Generated by Django 4.1 on 2022-08-26 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_banneraboutuspage_bannerhomepage_bannernewspage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bannertourpage',
            old_name='file1',
            new_name='file',
        ),
        migrations.RemoveField(
            model_name='bannertourpage',
            name='file2',
        ),
        migrations.RemoveField(
            model_name='bannertourpage',
            name='file3',
        ),
    ]
