# Generated by Django 4.1 on 2022-08-27 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0009_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Отзывы Клиентов',
            },
        ),
    ]
