# Generated by Django 4.1 on 2022-08-27 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0010_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='show',
            field=models.BooleanField(default=False),
        ),
    ]
