# Generated by Django 4.1 on 2022-08-27 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0011_feedback_show'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('headline', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'О Нас',
            },
        ),
        migrations.CreateModel(
            name='AboutCompanyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about_us_image/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.aboutcompany')),
            ],
            options={
                'verbose_name_plural': 'Добавит Фото',
            },
        ),
    ]
