# Generated by Django 4.1 on 2022-08-27 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0012_aboutcompany_aboutcompanyimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banneraboutuspage',
            name='file2',
        ),
        migrations.RemoveField(
            model_name='banneraboutuspage',
            name='file3',
        ),
    ]
