# Generated by Django 4.1 on 2022-08-27 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0013_remove_banneraboutuspage_file2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('profession', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='team_image/')),
            ],
            options={
                'verbose_name_plural': 'Наши Сотрудники',
            },
        ),
    ]
