# Generated by Django 4.1 on 2022-08-27 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0014_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Транспорт',
            },
        ),
        migrations.AlterModelOptions(
            name='aboutcompanyimage',
            options={'verbose_name_plural': 'Добавить Фото'},
        ),
        migrations.CreateModel(
            name='TransportImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='transport_image/')),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.transport')),
            ],
            options={
                'verbose_name_plural': 'Добавить Фото',
            },
        ),
    ]
