# Generated by Django 4.1 on 2022-08-27 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0015_transport_alter_aboutcompanyimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportimage',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
