# Generated by Django 4.1 on 2022-08-27 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0016_transportimage_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutcountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='about_country_image/')),
            ],
            options={
                'verbose_name_plural': 'О стране',
            },
        ),
    ]
