# Generated by Django 4.1 on 2022-08-27 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0017_aboutcountry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='geography_image/')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'География',
            },
        ),
    ]
