# Generated by Django 4.1 on 2022-08-27 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0018_geography'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='tour_information_image/')),
                ('video', models.FileField(blank=True, null=True, upload_to='tour_information_image/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Информация о путишествии',
            },
        ),
    ]
