# Generated by Django 4.1 on 2022-08-27 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0020_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannernewspage',
            name='file2',
        ),
        migrations.RemoveField(
            model_name='bannernewspage',
            name='file3',
        ),
    ]
