# Generated by Django 4.1 on 2022-08-27 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0021_remove_bannernewspage_file2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bannernewspage',
            old_name='file1',
            new_name='file',
        ),
    ]
